import type { DesignTemplate } from '../types';

export const designTemplates: DesignTemplate[] = [
  // ─── 1. Modern Corporate (기본값 — 현재 하드코딩된 값 그대로) ───
  {
    id: 'modern-corporate',
    name: 'Modern Corporate',
    nameKo: '모던 비즈니스',
    description: 'Structured headers, sidebar accent, grid overlay — the default professional look.',
    descriptionKo: '구조적 헤더, 사이드바 악센트, 그리드 오버레이 — 기본 비즈니스 디자인',
    category: 'business',
    layout: {
      sidebar: { enabled: true, width: 36, accentHeight: 80 },
      marginX: 57,
      contentMarginX: 94,
      sectionSpacing: 250,
      sectionStartY: 230,
      chapterBox: { enabled: true, shape: 'square', size: 54 },
      footer: { lineColor: '#D6D0C2', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 42, fontWeight: 800, letterSpacing: '-0.025em', lineHeight: 1.18 },
      coverSubtitle: { fontSize: 13, fontWeight: 600, letterSpacing: '0.04em' },
      bodyText: { fontSize: 13.3, fontWeight: 400, lineHeight: 1.75, textAlign: 'justify' },
      sectionTitle: { fontSize: 23, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 27, fontWeight: 900, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 34, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 48, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.5,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 84,
        categoryChip: { shape: 'square' },
      },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 120 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 205 },
      codeBlock: { background: '#F8F8F8', borderLeftWidth: 3 },
    },
  },

  // ─── 2. Minimal Clean ───
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    nameKo: '미니멀 클린',
    description: 'No sidebar, no decorations, center-aligned with generous whitespace.',
    descriptionKo: '사이드바 없음, 장식 없음, 중앙 정렬, 넓은 여백의 깔끔한 디자인',
    category: 'minimal',
    coverLayoutVariant: 'minimal-frame',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 80,
      contentMarginX: 80,
      sectionSpacing: 220,
      sectionStartY: 200,
      chapterBox: { enabled: false, shape: 'square', size: 0 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'pad2' },
      headerY: 40,
      headerLineY: 66,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 40, fontWeight: 700, letterSpacing: '-0.02em', lineHeight: 1.25 },
      coverSubtitle: { fontSize: 14, fontWeight: 400, letterSpacing: '0.02em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 22, fontWeight: 700 },
      chapterLabel: { fontSize: 11, fontWeight: 600, letterSpacing: '0.2em' },
      chapterTitle: { fontSize: 26, fontWeight: 700, lineHeight: 1.3 },
      labelText: { fontSize: 10, fontWeight: 600, letterSpacing: '0.2em' },
      tocTitle: { fontSize: 32, fontWeight: 700, lineHeight: 1.15 },
      summaryHeadline: { fontSize: 44, fontWeight: 700, letterSpacing: '-0.02em', lineHeight: 1.2 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.45,
        gridOverlay: false,
        cornerAccents: false,
        cornerSize: 0,
        categoryChip: { shape: 'pill' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 8, borderLeftWidth: 4 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 180, accentBarWidth: 80, accentBarHeight: 4 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: true, headerHeight: 32 },
      toc: { accentBarWidth: 40, accentBarHeight: 2, sectionSpacing: 200 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 3 },
    },
  },

  // ─── 3. Bold Gradient ───
  {
    id: 'bold-gradient',
    name: 'Bold Gradient',
    nameKo: '볼드 그라디언트',
    description: 'Rounded corners, large typography, energetic layout with pill-shaped chips.',
    descriptionKo: '둥근 모서리, 큰 타이포그래피, 에너지 넘치는 레이아웃',
    category: 'creative',
    coverLayoutVariant: 'diagonal-split',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: true, width: 28, accentHeight: 60 },
      marginX: 57,
      contentMarginX: 80,
      sectionSpacing: 260,
      sectionStartY: 240,
      chapterBox: { enabled: true, shape: 'rounded', size: 56 },
      footer: { lineColor: '#E0D6CC', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 48, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.12 },
      coverSubtitle: { fontSize: 14, fontWeight: 600, letterSpacing: '0.06em' },
      bodyText: { fontSize: 13.5, fontWeight: 400, lineHeight: 1.75, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 36, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 52, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.55,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 100,
        categoryChip: { shape: 'pill' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 12, borderLeftWidth: 6 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 220, accentBarWidth: 140, accentBarHeight: 8 },
      summary: { dotPattern: true, cornerMarkSize: 140 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 13, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: true, headerHeight: 34 },
      toc: { accentBarWidth: 70, accentBarHeight: 4, sectionSpacing: 210 },
      codeBlock: { background: '#F0F0F0', borderLeftWidth: 4 },
    },
  },

  // ─── 4. Classic Formal ───
  {
    id: 'classic-formal',
    name: 'Classic Formal',
    nameKo: '클래식 포멀',
    description: 'Serif typography, double-line borders, traditional numbering — academic elegance.',
    descriptionKo: '세리프 계열, 이중선 테두리, 전통적 번호 매김 — 학술 스타일',
    category: 'academic',
    coverLayoutVariant: 'top-panel',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 65,
      contentMarginX: 80,
      sectionSpacing: 240,
      sectionStartY: 220,
      chapterBox: { enabled: false, shape: 'square', size: 0 },
      footer: { lineColor: '#A89F91', pageNumberFormat: 'dash' },
      headerY: 40,
      headerLineY: 64,
    },
    typography: {
      fontFamily: "'Noto Serif KR', 'Batang', 'Georgia', serif",
      coverHeadline: { fontSize: 38, fontWeight: 700, letterSpacing: '0em', lineHeight: 1.3 },
      coverSubtitle: { fontSize: 14, fontWeight: 400, letterSpacing: '0.06em' },
      bodyText: { fontSize: 13.5, fontWeight: 400, lineHeight: 1.85, textAlign: 'justify' },
      sectionTitle: { fontSize: 22, fontWeight: 700 },
      chapterLabel: { fontSize: 11, fontWeight: 700, letterSpacing: '0.25em' },
      chapterTitle: { fontSize: 26, fontWeight: 700, lineHeight: 1.3 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.25em' },
      tocTitle: { fontSize: 32, fontWeight: 700, lineHeight: 1.15 },
      summaryHeadline: { fontSize: 42, fontWeight: 700, letterSpacing: '0em', lineHeight: 1.2 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.48,
        gridOverlay: false,
        cornerAccents: false,
        cornerSize: 0,
        categoryChip: { shape: 'square' },
      },
      bulletStyle: 'dash',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 4 },
      dividerStyle: 'double',
      sectionCover: { partNumberFontSize: 160, accentBarWidth: 100, accentBarHeight: 3 },
      summary: { dotPattern: false, cornerMarkSize: 80 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 10, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 28 },
      toc: { accentBarWidth: 50, accentBarHeight: 2, sectionSpacing: 200 },
      codeBlock: { background: '#F5F3EF', borderLeftWidth: 3 },
    },
  },

  // ─── 5. Tech Startup ───
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    nameKo: '테크 스타트업',
    description: 'Monospace accents, tight grid, code-friendly — perfect for tech presentations.',
    descriptionKo: '모노스페이스 악센트, 타이트한 그리드, 코드 친화적 디자인',
    category: 'creative',
    coverLayoutVariant: 'diagonal-split',
    contentLayoutVariant: 'default',
    layout: {
      sidebar: { enabled: true, width: 4, accentHeight: 60 },
      marginX: 57,
      contentMarginX: 70,
      sectionSpacing: 230,
      sectionStartY: 210,
      chapterBox: { enabled: true, shape: 'square', size: 48 },
      footer: { lineColor: '#CCCCCC', pageNumberFormat: 'pad3' },
      headerY: 32,
      headerLineY: 56,
    },
    typography: {
      fontFamily: "'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 40, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 12, fontWeight: 600, letterSpacing: '0.08em' },
      bodyText: { fontSize: 13, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 22, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      chapterTitle: { fontSize: 25, fontWeight: 800, lineHeight: 1.25 },
      labelText: { fontSize: 9, fontWeight: 700, letterSpacing: '0.3em' },
      tocTitle: { fontSize: 32, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.5,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 60,
        categoryChip: { shape: 'rounded' },
      },
      bulletStyle: 'dash',
      calloutStyle: { borderRadius: 4, borderLeftWidth: 4 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 180, accentBarWidth: 100, accentBarHeight: 4 },
      summary: { dotPattern: true, cornerMarkSize: 100 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 4, cardBorder: true, headerHeight: 28 },
      toc: { accentBarWidth: 50, accentBarHeight: 3, sectionSpacing: 195 },
      codeBlock: { background: '#1E1E1E', borderLeftWidth: 0 },
    },
  },

  // ─── 6. Magazine ───
  {
    id: 'magazine',
    name: 'Magazine',
    nameKo: '매거진',
    description: 'Editorial style with full-width quotes, thin rule lines, and wide letter spacing.',
    descriptionKo: '에디토리얼 스타일, 풀쿼트, 얇은 룰 라인의 매거진 디자인',
    category: 'creative',
    coverLayoutVariant: 'minimal-frame',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 60,
      contentMarginX: 75,
      sectionSpacing: 245,
      sectionStartY: 220,
      chapterBox: { enabled: true, shape: 'square', size: 50 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad2' },
      headerY: 36,
      headerLineY: 60,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 13, fontWeight: 500, letterSpacing: '0.1em' },
      bodyText: { fontSize: 13.5, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.35em' },
      chapterTitle: { fontSize: 27, fontWeight: 800, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.35em' },
      tocTitle: { fontSize: 34, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 46, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.6,
        gridOverlay: false,
        cornerAccents: false,
        cornerSize: 0,
        categoryChip: { shape: 'square' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 8 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 190, accentBarWidth: 130, accentBarHeight: 5 },
      summary: { dotPattern: false, cornerMarkSize: 100 },
      workbook: { stepBlockSize: 85, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 205 },
      codeBlock: { background: '#F6F6F6', borderLeftWidth: 4 },
    },
  },

  // ─── 7. Education Pro ───
  {
    id: 'education',
    name: 'Education Pro',
    nameKo: '교육 전문',
    description: 'Learning-focused with step highlights, colorful callouts, and checklists.',
    descriptionKo: '학습 단계 강조, 컬러풀 콜아웃, 체크리스트 중심의 교육 디자인',
    category: 'academic',
    coverLayoutVariant: 'left-panel',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: true, width: 40, accentHeight: 90 },
      marginX: 57,
      contentMarginX: 100,
      sectionSpacing: 255,
      sectionStartY: 240,
      chapterBox: { enabled: true, shape: 'circle', size: 60 },
      footer: { lineColor: '#D6D0C2', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 42, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 13, fontWeight: 600, letterSpacing: '0.04em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 23, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 27, fontWeight: 900, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 34, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 48, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.5,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 90,
        categoryChip: { shape: 'rounded' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 8, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 120 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 13, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 8, cardBorder: true, headerHeight: 32 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 210 },
      codeBlock: { background: '#F8F8F8', borderLeftWidth: 3 },
    },
  },

  // ─── 8. Elegant ───
  {
    id: 'elegant',
    name: 'Elegant',
    nameKo: '엘레강스',
    description: 'Hairline borders, light-weight fonts, refined spacing — understated sophistication.',
    descriptionKo: '헤어라인 테두리, 라이트 웨이트 폰트, 세련된 간격의 우아한 디자인',
    category: 'minimal',
    coverLayoutVariant: 'center-band',
    contentLayoutVariant: 'default',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 100,
      sectionSpacing: 235,
      sectionStartY: 215,
      chapterBox: { enabled: false, shape: 'square', size: 0 },
      footer: { lineColor: '#D8D8D8', pageNumberFormat: 'dash' },
      headerY: 44,
      headerLineY: 68,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 38, fontWeight: 300, letterSpacing: '0.02em', lineHeight: 1.3 },
      coverSubtitle: { fontSize: 13, fontWeight: 400, letterSpacing: '0.08em' },
      bodyText: { fontSize: 13.5, fontWeight: 300, lineHeight: 1.85, textAlign: 'left' },
      sectionTitle: { fontSize: 21, fontWeight: 600 },
      chapterLabel: { fontSize: 11, fontWeight: 500, letterSpacing: '0.35em' },
      chapterTitle: { fontSize: 25, fontWeight: 600, lineHeight: 1.3 },
      labelText: { fontSize: 10, fontWeight: 500, letterSpacing: '0.35em' },
      tocTitle: { fontSize: 30, fontWeight: 600, lineHeight: 1.15 },
      summaryHeadline: { fontSize: 42, fontWeight: 300, letterSpacing: '0.02em', lineHeight: 1.25 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.48,
        gridOverlay: false,
        cornerAccents: true,
        cornerSize: 60,
        categoryChip: { shape: 'pill' },
      },
      bulletStyle: 'none',
      calloutStyle: { borderRadius: 4, borderLeftWidth: 3 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 170, accentBarWidth: 90, accentBarHeight: 2 },
      summary: { dotPattern: false, cornerMarkSize: 60 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 11, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 8, cardBorder: false, headerHeight: 30 },
      toc: { accentBarWidth: 50, accentBarHeight: 1, sectionSpacing: 200 },
      codeBlock: { background: '#FAFAFA', borderLeftWidth: 2 },
    },
  },

  // ─── 9. Pitch Deck ───
  {
    id: 'pitch-deck',
    name: 'Pitch Deck',
    nameKo: '피치 덱',
    description: 'Large impact numbers, minimal text, bold statements — ideal for investor pitches.',
    descriptionKo: '큰 임팩트 숫자, 최소 텍스트, 강렬한 메시지 — 투자 발표용',
    category: 'business',
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 70,
      sectionSpacing: 270,
      sectionStartY: 230,
      chapterBox: { enabled: false, shape: 'circle', size: 64 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'pad2' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 52, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.08 },
      coverSubtitle: { fontSize: 15, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 15, fontWeight: 400, lineHeight: 1.85, textAlign: 'left' },
      sectionTitle: { fontSize: 26, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 30, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 38, fontWeight: 900, lineHeight: 1.05 },
      summaryHeadline: { fontSize: 56, fontWeight: 900, letterSpacing: '-0.04em', lineHeight: 1.05 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.55,
        gridOverlay: false,
        cornerAccents: false,
        cornerSize: 0,
        categoryChip: { shape: 'pill' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 16, borderLeftWidth: 6 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 240, accentBarWidth: 160, accentBarHeight: 8 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 14, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 16, cardBorder: false, headerHeight: 36 },
      toc: { accentBarWidth: 80, accentBarHeight: 4, sectionSpacing: 215 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 4 },
    },
  },

  // ─── 10. Dark Professional ───
  {
    id: 'dark-professional',
    name: 'Dark Professional',
    nameKo: '다크 프로페셔널',
    description: 'Dark tones with high contrast — dramatic look for keynotes and tech talks.',
    descriptionKo: '어두운 톤과 높은 대비 — 기조연설, IT 발표에 적합한 드라마틱 디자인',
    category: 'business',
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 57,
      contentMarginX: 80,
      sectionSpacing: 240,
      sectionStartY: 220,
      chapterBox: { enabled: false, shape: 'rounded', size: 52 },
      footer: { lineColor: '#444444', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 13, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 13.5, fontWeight: 400, lineHeight: 1.75, textAlign: 'left' },
      sectionTitle: { fontSize: 23, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 27, fontWeight: 800, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 34, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 48, fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.52,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 70,
        categoryChip: { shape: 'rounded' },
      },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 6, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 110 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'rounded', checkboxShape: 'square', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 6, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 205 },
      codeBlock: { background: '#1A1A2E', borderLeftWidth: 3 },
    },
  },

  // ─── 11. Infographic ───
  {
    id: 'infographic',
    name: 'Infographic',
    nameKo: '인포그래픽',
    description: 'Data-centric layout with bold numbers, icon-friendly blocks, and visual hierarchy.',
    descriptionKo: '데이터 중심 레이아웃, 굵은 숫자, 시각 계층 강조 디자인',
    category: 'creative',
    coverLayoutVariant: 'left-panel',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 50,
      contentMarginX: 70,
      sectionSpacing: 225,
      sectionStartY: 210,
      chapterBox: { enabled: false, shape: 'circle', size: 56 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad3' },
      headerY: 34,
      headerLineY: 58,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 44, fontWeight: 900, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 13, fontWeight: 600, letterSpacing: '0.05em' },
      bodyText: { fontSize: 13, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 900 },
      chapterLabel: { fontSize: 10, fontWeight: 800, letterSpacing: '0.32em' },
      chapterTitle: { fontSize: 28, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 9, fontWeight: 800, letterSpacing: '0.3em' },
      tocTitle: { fontSize: 34, fontWeight: 900, lineHeight: 1.08 },
      summaryHeadline: { fontSize: 50, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.48,
        gridOverlay: true,
        cornerAccents: true,
        cornerSize: 80,
        categoryChip: { shape: 'rounded' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 10, borderLeftWidth: 6 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 220, accentBarWidth: 140, accentBarHeight: 7 },
      summary: { dotPattern: true, cornerMarkSize: 130 },
      workbook: { stepBlockSize: 95, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 13, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 10, cardBorder: true, headerHeight: 34 },
      toc: { accentBarWidth: 70, accentBarHeight: 4, sectionSpacing: 200 },
      codeBlock: { background: '#F0F4F8', borderLeftWidth: 4 },
    },
  },

  // ─── 12. Nature Organic ───
  {
    id: 'nature-organic',
    name: 'Nature Organic',
    nameKo: '내추럴 오가닉',
    description: 'Soft curves, generous margins, organic shapes — for wellness and sustainability topics.',
    descriptionKo: '부드러운 곡선, 넉넉한 여백, 유기적 형태 — 자연, 웰빙, 환경 주제에 적합',
    category: 'minimal',
    coverLayoutVariant: 'center-band',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 75,
      contentMarginX: 90,
      sectionSpacing: 240,
      sectionStartY: 215,
      chapterBox: { enabled: false, shape: 'circle', size: 50 },
      footer: { lineColor: '#D4D9D0', pageNumberFormat: 'plain' },
      headerY: 42,
      headerLineY: 66,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 40, fontWeight: 600, letterSpacing: '-0.01em', lineHeight: 1.28 },
      coverSubtitle: { fontSize: 14, fontWeight: 400, letterSpacing: '0.04em' },
      bodyText: { fontSize: 14, fontWeight: 300, lineHeight: 1.9, textAlign: 'left' },
      sectionTitle: { fontSize: 22, fontWeight: 700 },
      chapterLabel: { fontSize: 11, fontWeight: 600, letterSpacing: '0.25em' },
      chapterTitle: { fontSize: 26, fontWeight: 700, lineHeight: 1.3 },
      labelText: { fontSize: 10, fontWeight: 600, letterSpacing: '0.25em' },
      tocTitle: { fontSize: 32, fontWeight: 700, lineHeight: 1.15 },
      summaryHeadline: { fontSize: 44, fontWeight: 600, letterSpacing: '-0.01em', lineHeight: 1.2 },
    },
    decorations: {
      cover: {
        topPanelRatio: 0.46,
        gridOverlay: false,
        cornerAccents: false,
        cornerSize: 0,
        categoryChip: { shape: 'pill' },
      },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 14, borderLeftWidth: 4 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 170, accentBarWidth: 80, accentBarHeight: 3 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 14, cardBorder: false, headerHeight: 32 },
      toc: { accentBarWidth: 40, accentBarHeight: 2, sectionSpacing: 205 },
      codeBlock: { background: '#F4F7F2', borderLeftWidth: 3 },
    },
  },

  // ═══════════════════════════════════════════
  // 가로형 (Landscape) — 1123×794
  // ═══════════════════════════════════════════

  // ─── 13. Wide Modern ───
  {
    id: 'wide-modern',
    name: 'Wide Modern',
    nameKo: '와이드 모던',
    description: 'Landscape variant of Modern Corporate — wide sidebar accent, grid overlay.',
    descriptionKo: '모던 비즈니스의 가로 버전 — 와이드 사이드바, 그리드 오버레이',
    category: 'business',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    layout: {
      sidebar: { enabled: true, width: 36, accentHeight: 80 },
      marginX: 57,
      contentMarginX: 94,
      sectionSpacing: 200,
      sectionStartY: 180,
      chapterBox: { enabled: true, shape: 'square', size: 54 },
      footer: { lineColor: '#D6D0C2', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.025em', lineHeight: 1.18 },
      coverSubtitle: { fontSize: 14, fontWeight: 600, letterSpacing: '0.04em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.75, textAlign: 'justify' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 900, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 36, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 50, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.45, gridOverlay: true, cornerAccents: true, cornerSize: 84, categoryChip: { shape: 'square' } },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 120 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 170 },
      codeBlock: { background: '#F8F8F8', borderLeftWidth: 3 },
    },
  },

  // ─── 14. Wide Minimal ───
  {
    id: 'wide-minimal',
    name: 'Wide Minimal',
    nameKo: '와이드 미니멀',
    description: 'Landscape variant of Minimal Clean — expansive whitespace, center-aligned.',
    descriptionKo: '미니멀 클린의 가로 버전 — 넓은 여백, 중앙 정렬',
    category: 'minimal',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    coverLayoutVariant: 'minimal-frame',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 80,
      contentMarginX: 80,
      sectionSpacing: 180,
      sectionStartY: 160,
      chapterBox: { enabled: false, shape: 'square', size: 0 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'pad2' },
      headerY: 40,
      headerLineY: 66,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 42, fontWeight: 700, letterSpacing: '-0.02em', lineHeight: 1.25 },
      coverSubtitle: { fontSize: 15, fontWeight: 400, letterSpacing: '0.02em' },
      bodyText: { fontSize: 15, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 700 },
      chapterLabel: { fontSize: 11, fontWeight: 600, letterSpacing: '0.2em' },
      chapterTitle: { fontSize: 28, fontWeight: 700, lineHeight: 1.3 },
      labelText: { fontSize: 10, fontWeight: 600, letterSpacing: '0.2em' },
      tocTitle: { fontSize: 34, fontWeight: 700, lineHeight: 1.15 },
      summaryHeadline: { fontSize: 46, fontWeight: 700, letterSpacing: '-0.02em', lineHeight: 1.2 },
    },
    decorations: {
      cover: { topPanelRatio: 0.4, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 8, borderLeftWidth: 4 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 180, accentBarWidth: 80, accentBarHeight: 4 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: true, headerHeight: 32 },
      toc: { accentBarWidth: 40, accentBarHeight: 2, sectionSpacing: 170 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 3 },
    },
  },

  // ─── 15. Wide Bold ───
  {
    id: 'wide-bold',
    name: 'Wide Bold',
    nameKo: '와이드 볼드',
    description: 'Landscape variant of Bold Gradient — energetic layout with large typography.',
    descriptionKo: '볼드 그라디언트의 가로 버전 — 큰 타이포그래피, 에너지 넘치는 레이아웃',
    category: 'creative',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    coverLayoutVariant: 'diagonal-split',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: true, width: 28, accentHeight: 60 },
      marginX: 57,
      contentMarginX: 80,
      sectionSpacing: 210,
      sectionStartY: 190,
      chapterBox: { enabled: true, shape: 'rounded', size: 56 },
      footer: { lineColor: '#E0D6CC', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 50, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.12 },
      coverSubtitle: { fontSize: 15, fontWeight: 600, letterSpacing: '0.06em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.75, textAlign: 'left' },
      sectionTitle: { fontSize: 26, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 30, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 38, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 54, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
    },
    decorations: {
      cover: { topPanelRatio: 0.5, gridOverlay: true, cornerAccents: true, cornerSize: 100, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 12, borderLeftWidth: 6 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 220, accentBarWidth: 140, accentBarHeight: 8 },
      summary: { dotPattern: true, cornerMarkSize: 140 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 13, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: true, headerHeight: 34 },
      toc: { accentBarWidth: 70, accentBarHeight: 4, sectionSpacing: 180 },
      codeBlock: { background: '#F0F0F0', borderLeftWidth: 4 },
    },
  },

  // ─── 16. Wide Dark ───
  {
    id: 'wide-dark',
    name: 'Wide Dark',
    nameKo: '와이드 다크',
    description: 'Landscape variant of Dark Professional — dramatic, high-contrast widescreen.',
    descriptionKo: '다크 프로페셔널의 가로 버전 — 드라마틱한 와이드스크린 디자인',
    category: 'business',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 57,
      contentMarginX: 80,
      sectionSpacing: 200,
      sectionStartY: 180,
      chapterBox: { enabled: false, shape: 'rounded', size: 52 },
      footer: { lineColor: '#444444', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 46, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 14, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.75, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 800, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 36, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 50, fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.48, gridOverlay: true, cornerAccents: true, cornerSize: 70, categoryChip: { shape: 'rounded' } },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 6, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 110 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'rounded', checkboxShape: 'square', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 6, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 170 },
      codeBlock: { background: '#1A1A2E', borderLeftWidth: 3 },
    },
  },

  // ─── 17. Wide Pitch ───
  {
    id: 'wide-pitch',
    name: 'Wide Pitch',
    nameKo: '와이드 피치덱',
    description: 'Landscape variant of Pitch Deck — large impact numbers on wide canvas.',
    descriptionKo: '피치 덱의 가로 버전 — 큰 숫자, 강렬한 메시지의 와이드 캔버스',
    category: 'business',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 70,
      sectionSpacing: 220,
      sectionStartY: 190,
      chapterBox: { enabled: false, shape: 'circle', size: 64 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'pad2' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 54, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.08 },
      coverSubtitle: { fontSize: 16, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 16, fontWeight: 400, lineHeight: 1.85, textAlign: 'left' },
      sectionTitle: { fontSize: 28, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 32, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 40, fontWeight: 900, lineHeight: 1.05 },
      summaryHeadline: { fontSize: 58, fontWeight: 900, letterSpacing: '-0.04em', lineHeight: 1.05 },
    },
    decorations: {
      cover: { topPanelRatio: 0.5, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 16, borderLeftWidth: 6 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 240, accentBarWidth: 160, accentBarHeight: 8 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 14, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 16, cardBorder: false, headerHeight: 36 },
      toc: { accentBarWidth: 80, accentBarHeight: 4, sectionSpacing: 180 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 4 },
    },
  },

  // ─── 18. Wide Creative ───
  {
    id: 'wide-creative',
    name: 'Wide Creative',
    nameKo: '와이드 크리에이티브',
    description: 'Landscape variant of Magazine — editorial layout on wide canvas.',
    descriptionKo: '매거진의 가로 버전 — 에디토리얼 스타일 와이드 캔버스',
    category: 'creative',
    orientation: 'landscape',
    canvasSize: { width: 1123, height: 794 },
    coverLayoutVariant: 'minimal-frame',
    contentLayoutVariant: 'top-accent',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 60,
      contentMarginX: 75,
      sectionSpacing: 200,
      sectionStartY: 180,
      chapterBox: { enabled: true, shape: 'square', size: 50 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad2' },
      headerY: 36,
      headerLineY: 60,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 46, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 14, fontWeight: 500, letterSpacing: '0.1em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 26, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.35em' },
      chapterTitle: { fontSize: 28, fontWeight: 800, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.35em' },
      tocTitle: { fontSize: 36, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 48, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.55, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'square' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 8 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 190, accentBarWidth: 130, accentBarHeight: 5 },
      summary: { dotPattern: false, cornerMarkSize: 100 },
      workbook: { stepBlockSize: 85, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 175 },
      codeBlock: { background: '#F6F6F6', borderLeftWidth: 4 },
    },
  },

  // ═══════════════════════════════════════════
  // 커스텀 사이즈 (Custom)
  // ═══════════════════════════════════════════

  // ─── 19. Square SNS (1080×1080) ───
  {
    id: 'square-sns',
    name: 'Square SNS',
    nameKo: 'SNS 정방형',
    description: 'Square format for Instagram and social media posts — 1080×1080.',
    descriptionKo: '인스타그램/소셜 미디어 정방형 포맷 — 1080×1080',
    category: 'creative',
    orientation: 'custom',
    canvasSize: { width: 1080, height: 1080 },
    coverLayoutVariant: 'center-band',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 60,
      contentMarginX: 60,
      sectionSpacing: 200,
      sectionStartY: 180,
      chapterBox: { enabled: false, shape: 'rounded', size: 50 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'plain' },
      headerY: 36,
      headerLineY: 60,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 48, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 15, fontWeight: 500, letterSpacing: '0.04em' },
      bodyText: { fontSize: 15, fontWeight: 400, lineHeight: 1.75, textAlign: 'left' },
      sectionTitle: { fontSize: 26, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 800, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 36, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 50, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
    },
    decorations: {
      cover: { topPanelRatio: 0.45, gridOverlay: false, cornerAccents: true, cornerSize: 70, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 12, borderLeftWidth: 5 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: false, cornerMarkSize: 80 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: true, headerHeight: 32 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 180 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 3 },
    },
  },

  // ─── 20. Ultra Wide (1400×600) ───
  {
    id: 'ultra-wide',
    name: 'Ultra Wide',
    nameKo: '울트라 와이드',
    description: 'Ultra-wide banner format for displays and digital signage — 1400×600.',
    descriptionKo: '배너/디스플레이용 울트라 와이드 포맷 — 1400×600',
    category: 'creative',
    orientation: 'custom',
    canvasSize: { width: 1400, height: 600 },
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 80,
      contentMarginX: 80,
      sectionSpacing: 160,
      sectionStartY: 140,
      chapterBox: { enabled: false, shape: 'rounded', size: 48 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad2' },
      headerY: 32,
      headerLineY: 56,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 42, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 14, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 26, fontWeight: 800, lineHeight: 1.2 },
      labelText: { fontSize: 9, fontWeight: 700, letterSpacing: '0.3em' },
      tocTitle: { fontSize: 34, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.4, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 8, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 160, accentBarWidth: 100, accentBarHeight: 5 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 8, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 50, accentBarHeight: 3, sectionSpacing: 150 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 3 },
    },
  },

  // ─── 21. US Letter (1056×816) ───
  {
    id: 'letter-us',
    name: 'US Letter',
    nameKo: 'US Letter',
    description: 'US Letter standard format for American paper size — 1056×816.',
    descriptionKo: '미국 표준 용지(US Letter) 포맷 — 1056×816',
    category: 'business',
    orientation: 'custom',
    canvasSize: { width: 1056, height: 816 },
    coverLayoutVariant: 'top-panel',
    contentLayoutVariant: 'default',
    layout: {
      sidebar: { enabled: true, width: 36, accentHeight: 80 },
      marginX: 60,
      contentMarginX: 90,
      sectionSpacing: 210,
      sectionStartY: 190,
      chapterBox: { enabled: true, shape: 'square', size: 52 },
      footer: { lineColor: '#D6D0C2', pageNumberFormat: 'pad3' },
      headerY: 36,
      headerLineY: 62,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 42, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 14, fontWeight: 600, letterSpacing: '0.04em' },
      bodyText: { fontSize: 14, fontWeight: 400, lineHeight: 1.75, textAlign: 'justify' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 11, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 900, lineHeight: 1.25 },
      labelText: { fontSize: 10, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 34, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 48, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.48, gridOverlay: true, cornerAccents: true, cornerSize: 80, categoryChip: { shape: 'square' } },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 200, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: true, cornerMarkSize: 110 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 11, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 180 },
      codeBlock: { background: '#F8F8F8', borderLeftWidth: 3 },
    },
  },

  // ─── 22. Custom Compact 4:3 (800×600) ───
  {
    id: 'custom-compact',
    name: 'Compact 4:3',
    nameKo: '컴팩트 4:3',
    description: 'Classic 4:3 format for older projectors and legacy displays — 800×600.',
    descriptionKo: '구형 프로젝터/레거시 디스플레이용 4:3 포맷 — 800×600',
    category: 'business',
    orientation: 'custom',
    canvasSize: { width: 800, height: 600 },
    coverLayoutVariant: 'top-panel',
    contentLayoutVariant: 'default',
    layout: {
      sidebar: { enabled: true, width: 30, accentHeight: 60 },
      marginX: 50,
      contentMarginX: 80,
      sectionSpacing: 170,
      sectionStartY: 160,
      chapterBox: { enabled: true, shape: 'square', size: 48 },
      footer: { lineColor: '#D6D0C2', pageNumberFormat: 'pad2' },
      headerY: 32,
      headerLineY: 56,
    },
    typography: {
      fontFamily: "'Malgun Gothic', '맑은 고딕', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 36, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 12, fontWeight: 600, letterSpacing: '0.04em' },
      bodyText: { fontSize: 13, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 20, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 800, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 24, fontWeight: 900, lineHeight: 1.25 },
      labelText: { fontSize: 9, fontWeight: 800, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 28, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 40, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.48, gridOverlay: true, cornerAccents: true, cornerSize: 70, categoryChip: { shape: 'square' } },
      bulletStyle: 'diamond',
      calloutStyle: { borderRadius: 0, borderLeftWidth: 4 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 160, accentBarWidth: 100, accentBarHeight: 5 },
      summary: { dotPattern: true, cornerMarkSize: 100 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'square', checkboxShape: 'square', checkboxSize: 10, checklistBorder: 'dashed' },
      diagram: { cardBorderRadius: 0, cardBorder: true, headerHeight: 28 },
      toc: { accentBarWidth: 50, accentBarHeight: 3, sectionSpacing: 160 },
      codeBlock: { background: '#F8F8F8', borderLeftWidth: 3 },
    },
  },

  // ═══════════════════════════════════════════
  // 카드뉴스 / SNS
  // ═══════════════════════════════════════════

  // ─── 23. 인스타그램 피드 카드뉴스 (1080×1350, 4:5) ───
  {
    id: 'card-insta-feed',
    name: 'Instagram Feed',
    nameKo: '인스타 피드 카드뉴스',
    description: 'Instagram feed card news — 4:5 vertical, optimized for carousel posts.',
    descriptionKo: '인스타그램 피드 카드뉴스 — 4:5 세로, 캐러셀 포스트에 최적화',
    category: 'creative',
    orientation: 'sns',
    canvasSize: { width: 1080, height: 1350 },
    coverLayoutVariant: 'center-band',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 70,
      sectionSpacing: 260,
      sectionStartY: 240,
      chapterBox: { enabled: false, shape: 'rounded', size: 56 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'plain' },
      headerY: 40,
      headerLineY: 66,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 54, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 16, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 18, fontWeight: 400, lineHeight: 1.8, textAlign: 'left' },
      sectionTitle: { fontSize: 30, fontWeight: 800 },
      chapterLabel: { fontSize: 12, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 34, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 11, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 40, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 56, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.42, gridOverlay: false, cornerAccents: true, cornerSize: 80, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 16, borderLeftWidth: 6 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 220, accentBarWidth: 140, accentBarHeight: 7 },
      summary: { dotPattern: false, cornerMarkSize: 90 },
      workbook: { stepBlockSize: 100, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 14, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 16, cardBorder: false, headerHeight: 36 },
      toc: { accentBarWidth: 70, accentBarHeight: 4, sectionSpacing: 220 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 4 },
    },
  },

  // ─── 24. 인스타그램 스토리 / 릴스 (1080×1920, 9:16) ───
  {
    id: 'card-insta-story',
    name: 'Instagram Story',
    nameKo: '인스타 스토리 / 릴스',
    description: 'Instagram Story & Reels — 9:16 full-screen vertical format.',
    descriptionKo: '인스타그램 스토리/릴스 — 9:16 풀스크린 세로 포맷',
    category: 'creative',
    orientation: 'sns',
    canvasSize: { width: 1080, height: 1920 },
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'card-grid',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 70,
      sectionSpacing: 340,
      sectionStartY: 320,
      chapterBox: { enabled: false, shape: 'rounded', size: 60 },
      footer: { lineColor: '#E0E0E0', pageNumberFormat: 'plain' },
      headerY: 50,
      headerLineY: 80,
    },
    typography: {
      fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
      coverHeadline: { fontSize: 60, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.2 },
      coverSubtitle: { fontSize: 18, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 20, fontWeight: 400, lineHeight: 1.85, textAlign: 'left' },
      sectionTitle: { fontSize: 34, fontWeight: 800 },
      chapterLabel: { fontSize: 13, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 38, fontWeight: 900, lineHeight: 1.2 },
      labelText: { fontSize: 12, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 44, fontWeight: 900, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 62, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.38, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 20, borderLeftWidth: 7 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 260, accentBarWidth: 160, accentBarHeight: 8 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 110, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 15, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 20, cardBorder: false, headerHeight: 40 },
      toc: { accentBarWidth: 80, accentBarHeight: 5, sectionSpacing: 280 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 5 },
    },
  },

  // ─── 25. 페이스북 피드 카드뉴스 (1200×630, 약 1.9:1) ───
  {
    id: 'card-facebook',
    name: 'Facebook Feed',
    nameKo: '페이스북 피드 카드뉴스',
    description: 'Facebook feed card news — 1200×630, optimized for link previews and shares.',
    descriptionKo: '페이스북 피드 카드뉴스 — 1200×630, 링크 프리뷰/공유에 최적화',
    category: 'creative',
    orientation: 'sns',
    canvasSize: { width: 1200, height: 630 },
    coverLayoutVariant: 'diagonal-split',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 60,
      contentMarginX: 60,
      sectionSpacing: 170,
      sectionStartY: 150,
      chapterBox: { enabled: false, shape: 'rounded', size: 48 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad2' },
      headerY: 30,
      headerLineY: 54,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
      coverSubtitle: { fontSize: 14, fontWeight: 500, letterSpacing: '0.06em' },
      bodyText: { fontSize: 15, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 24, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 26, fontWeight: 800, lineHeight: 1.2 },
      labelText: { fontSize: 9, fontWeight: 700, letterSpacing: '0.3em' },
      tocTitle: { fontSize: 34, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.15 },
    },
    decorations: {
      cover: { topPanelRatio: 0.45, gridOverlay: true, cornerAccents: true, cornerSize: 60, categoryChip: { shape: 'rounded' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 10, borderLeftWidth: 5 },
      dividerStyle: 'solid',
      sectionCover: { partNumberFontSize: 160, accentBarWidth: 100, accentBarHeight: 5 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 80, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 12, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 10, cardBorder: true, headerHeight: 30 },
      toc: { accentBarWidth: 50, accentBarHeight: 3, sectionSpacing: 150 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 3 },
    },
  },

  // ─── 26. 유튜브 썸네일 (1280×720, 16:9) ───
  {
    id: 'card-youtube',
    name: 'YouTube Thumbnail',
    nameKo: '유튜브 썸네일',
    description: 'YouTube thumbnail — 1280×720, 16:9 HD format for video covers.',
    descriptionKo: '유튜브 썸네일 — 1280×720, 16:9 HD 영상 커버용',
    category: 'creative',
    orientation: 'sns',
    canvasSize: { width: 1280, height: 720 },
    coverLayoutVariant: 'full-bleed',
    contentLayoutVariant: 'clean-wide',
    layout: {
      sidebar: { enabled: false, width: 0, accentHeight: 0 },
      marginX: 70,
      contentMarginX: 70,
      sectionSpacing: 190,
      sectionStartY: 170,
      chapterBox: { enabled: false, shape: 'rounded', size: 50 },
      footer: { lineColor: '#D0D0D0', pageNumberFormat: 'pad2' },
      headerY: 32,
      headerLineY: 56,
    },
    typography: {
      fontFamily: "'Pretendard', 'Malgun Gothic', sans-serif",
      coverHeadline: { fontSize: 52, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
      coverSubtitle: { fontSize: 15, fontWeight: 500, letterSpacing: '0.08em' },
      bodyText: { fontSize: 15, fontWeight: 400, lineHeight: 1.7, textAlign: 'left' },
      sectionTitle: { fontSize: 26, fontWeight: 800 },
      chapterLabel: { fontSize: 10, fontWeight: 700, letterSpacing: '0.3em' },
      chapterTitle: { fontSize: 28, fontWeight: 800, lineHeight: 1.2 },
      labelText: { fontSize: 10, fontWeight: 700, letterSpacing: '0.28em' },
      tocTitle: { fontSize: 36, fontWeight: 800, lineHeight: 1.1 },
      summaryHeadline: { fontSize: 50, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1 },
    },
    decorations: {
      cover: { topPanelRatio: 0.5, gridOverlay: false, cornerAccents: false, cornerSize: 0, categoryChip: { shape: 'pill' } },
      bulletStyle: 'circle',
      calloutStyle: { borderRadius: 12, borderLeftWidth: 5 },
      dividerStyle: 'none',
      sectionCover: { partNumberFontSize: 180, accentBarWidth: 120, accentBarHeight: 6 },
      summary: { dotPattern: false, cornerMarkSize: 0 },
      workbook: { stepBlockSize: 90, stepBlockShape: 'rounded', checkboxShape: 'circle', checkboxSize: 13, checklistBorder: 'solid' },
      diagram: { cardBorderRadius: 12, cardBorder: false, headerHeight: 32 },
      toc: { accentBarWidth: 60, accentBarHeight: 3, sectionSpacing: 165 },
      codeBlock: { background: '#F5F5F5', borderLeftWidth: 4 },
    },
  },
];

export function getDesignTemplate(id: string): DesignTemplate {
  return designTemplates.find(t => t.id === id) || designTemplates[0];
}
